name: CMake

on:
  pull_request:
    branches: "*"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  PROJECT_NAME: wasm-instrumentation
  DOCKER_IMAGE_NAME: wasm-instrumentation:latest
  DOCKER_RUN_COMMAND: docker run --rm -i -v ${{ github.workspace }}:/home/wasm-instrumentation wasm-instrumentation:latest bash -c

jobs:
  Build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - name: Submodule
        working-directory: ${{github.workspace}}/thirdparty
        run: git submodule update --init && cd binaryen && git submodule update --init
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          load: true

      - name: Clang-format check
        run: |
          ${{ env.DOCKER_RUN_COMMAND }} '
            find src test  -regex ".*\\.\\(cpp\\|hpp\\|c\\|h\\)" | xargs clang-format -style=file --Werror --dry-run
          '

      - name: Spell check
        run: |
          ${{ env.DOCKER_RUN_COMMAND }} '
            cspell "{src,test}/**/*.{hpp,cpp}"
          '

      - name: Build
        run: |
          ${{ env.DOCKER_RUN_COMMAND }} '
            cmake -B build -DENABLE_E2E=1 -DENABLE_FUZZ=1 -DENABLE_SANITIZE=1 -DENABLE_CLANG_TIDY=1 -DENABLE_WERROR=1 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++  -G Ninja
            cmake --build build --parallel
          '

      - name: Test Coverage
        run: |
          ${{ env.DOCKER_RUN_COMMAND }} '
            cd build
            ninja cov
          '

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./build/cov.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "90 90"

      - name: Build JS Variant
        uses: ./.github/actions/build-JS-variant
        with:
          DOCKER_RUN_COMMAND: ${{ env.DOCKER_RUN_COMMAND }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
